version: '3.6'
services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - "./database:/var/lib/mysql"
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        ports:
            - 8082:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
    www:
        build: '.'
        image: php:7.2-apache
        depends_on:
            - db
        ports: 
            - "8080:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db